import sys
from pathlib import Path
from datetime import datetime

# Add project root to Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from container import build_review_code_use_case  # noqa: E402


def validate_config():
    """Validate configuration and return status message."""
    import os

    # Check for API key from Google AI Studio
    api_key = os.getenv("GEMINI_API_KEY")
    if api_key:
        json_path = Path(api_key)
        if json_path.suffix == ".json" and json_path.exists():
            return (
                True,
                f"✓ Configuration valid: Using service account "
                f"({json_path.name})",
            )
        else:
            return (
                True,
                "✓ Configuration valid: Using GEMINI_API_KEY from AI Studio",
            )

    # Check for service account JSON file in project root
    project_root = Path(__file__).parent.parent
    json_files = list(project_root.glob("*.json"))
    for json_file in json_files:
        if (
            json_file.name.startswith("package")
            or json_file.name.startswith("tsconfig")
        ):
            continue
        try:
            # Try to build use case to validate
            _ = build_review_code_use_case()
            return (
                True,
                f"✓ Configuration valid: Using service account "
                f"({json_file.name})",
            )
        except Exception:
            continue

    return (
        False,
        "✗ Configuration invalid: No GEMINI_API_KEY or service account "
        "JSON file found. Get API key from: "
        "https://aistudio.google.com/apikey",
    )


def save_review_to_markdown(
    review_content: str, original_file_path: str, output_dir: Path = None
) -> str:
    """Save review to a markdown file."""
    if output_dir is None:
        output_dir = Path(__file__).parent.parent / "reviews"
    else:
        output_dir = Path(output_dir)

    # Create reviews directory if it doesn't exist
    output_dir.mkdir(exist_ok=True)

    # Generate filename based on original file
    original_path = Path(original_file_path)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_filename = (
        original_path.stem.replace(" ", "_")
        .replace("/", "_")
        .replace("\\", "_")
    )
    output_filename = f"{safe_filename}_review_{timestamp}.md"
    output_path = output_dir / output_filename

    # Create markdown content
    markdown_content = f"""# Code Review: {original_file_path}

**Reviewed on:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**File:** `{original_file_path}`

---

{review_content}

---

*Generated by CODE ROASTER 3000 🔥*
"""

    # Write to file
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(markdown_content)

    return str(output_path)


def review_file(use_case, file_path: str):
    """Review a single file and return the result."""
    path = Path(file_path)

    if not path.exists():
        return (
            None,
            None,
            f"💀 File not found: {file_path}\n"
            "   Did you even check if it exists? 🤦",
        )

    if not path.is_file():
        return (
            None,
            None,
            f"💀 That's not a file, genius: {file_path}\n"
            "   I need a FILE, not a directory! 📁",
        )

    try:
        with open(path, "r", encoding="utf-8") as f:
            code = f.read()

        if not code.strip():
            return (
                None,
                None,
                "💀 This file is EMPTY!\n"
                "   There's nothing to roast here... "
                "or is that the problem? 🤔",
            )

        print(f"\n🔥 Preparing to roast: {file_path}")
        print("⏳ Analyzing your code like a trainee wrote it...\n")

        result = use_case.execute(code)

        # Save to markdown file
        try:
            saved_path = save_review_to_markdown(result, file_path)
            return result, saved_path, None
        except Exception:
            # If saving fails, still return the result
            return result, None, None
    except Exception as e:
        return (
            None,
            None,
            f"💥 Error reviewing file: {str(e)}\n"
            "   Even I can't fix this mess!",
        )


def main():
    """Interactive CLI for code review."""
    # Welcome message with style
    print("\n" + "=" * 70)
    print("🔥" + " " * 20 + "CODE ROASTER 3000" + " " * 20 + "🔥")
    print("=" * 70)
    print("🤖 The AI that will be brutally honest about your code")
    print("💀 Prepare to be roasted (but also helped)")
    print("=" * 70 + "\n")

    # Validate configuration
    print("🔍 Checking if you're actually configured...")
    is_valid, message = validate_config()
    if is_valid:
        print(f"✅ {message}")
    else:
        print(f"❌ {message}")
    print()

    if not is_valid:
        print(
            "💀 Bruh, configure your API key first. "
            "Can't roast code without it."
        )
        sys.exit(1)

    # Build use case
    try:
        use_case = build_review_code_use_case()
    except Exception as e:
        print(f"💥 Oops! Failed to initialize: {str(e)}")
        sys.exit(1)

    print("✨ Ready to absolutely destroy your code (constructively)!")
    print()
    print("📋 Commands:")
    print("  - Enter a file path to get roasted 🔥")
    print("  - Type 'exit' or 'quit' to escape")
    print("  - Type 'help' if you're lost")
    print("-" * 70)
    print()

    # Interactive loop
    while True:
        try:
            file_path = input(
                "😈 Enter your code path (or 'exit' to quit): "
            ).strip()

            if not file_path:
                print("🤔 You typed... nothing? Try again, champ.\n")
                continue

            if file_path.lower() in ["exit", "quit", "q"]:
                print(
                    "\n👋 See ya! Hope your code survives without me! 💀\n"
                )
                break

            if file_path.lower() == "help":
                print(
                    "\n📖 Commands (because apparently you need help):"
                )
                print("  - Enter a file path (relative or absolute)")
                print(
                    "  - 'exit' or 'quit' - Escape this roasting session"
                )
                print("  - 'help' - You're already here, genius")
                print()
                continue

            result, saved_path, error = review_file(use_case, file_path)

            if error:
                print(f"💥 {error}\n")
            else:
                print("\n" + "=" * 70)
                print(
                    "🔥" + " " * 25 + "THE ROAST" + " " * 25 + "🔥"
                )
                print("=" * 70)
                print(result)
                print("=" * 70)

                if saved_path:
                    print(f"\n💾 Review saved to: {saved_path}")

                print("\n💀 Hope you learned something! "
                      "(You probably did)\n")

        except KeyboardInterrupt:
            print(
                "\n\n💀 Interrupted! Fine, I'll stop roasting "
                "your code... for now.\n"
            )
            break
        except EOFError:
            print("\n\n👋 Bye! Your code is safe... for now.\n")
            break


if __name__ == "__main__":
    # Support both interactive and non-interactive modes
    if len(sys.argv) > 1:
        # Non-interactive mode: single file review
        path = sys.argv[1]
        use_case = build_review_code_use_case()

        result, saved_path, error = review_file(use_case, path)
        if error:
            print(error, file=sys.stderr)
            sys.exit(1)
        else:
            print(result)
            if saved_path:
                print(f"\n💾 Review saved to: {saved_path}", file=sys.stderr)
    else:
        # Interactive mode
        main()
